//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public enum TYPE
{
	
	UNKNOWN = 0,
	FLOOR = 1,
	WALL = 2,
	STONE = 3
}
	public class TileData
	{
		public TileData ()
		{
		}
	}


